server:
  port: 8080
  servlet:
    context-path: /userdemo

spring:
  application:
    name: userdemo
  flyway:
    enabled: true
  datasource:
    url: jdbc:h2:mem:userdemo
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

minAge: 18
